name: window_decorations
description: A package which provides most of the window decorations from linux themes.
version: 0.9.0
homepage: https://github.com/prateekmedia/window_decorations

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  gsettings: ">=0.2.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/themes/adwaita/
    - assets/themes/ambiance/
    - assets/themes/arc-dark/
    - assets/themes/arc-light/
    - assets/themes/breeze/
    - assets/themes/flat-remix/
    - assets/themes/materia-dark/
    - assets/themes/materia-light/
    - assets/themes/nordic/
    - assets/themes/osx-arc/
    - assets/themes/pop-dark/
    - assets/themes/pop-light/
    - assets/themes/prof-gnome/
    - assets/themes/radiance/
    - assets/themes/telinkrin/
    - assets/themes/united-dark/
    - assets/themes/united-light/
    - assets/themes/unity-dark/
    - assets/themes/unity-light/
    - assets/themes/vertex/
    - assets/themes/vimix/
    - assets/themes/yaru/
